import type { Product } from './types'

export const mockProducts: Product[] = [
  {
    id: 'p-1',
    name: 'MacBook Pro 14"',
    sku: 'MBP14M3PRO',
    description: 'Laptop z procesorem M3 Pro',
    manufacturer: 'Apple',
    category: 'Komputery',
    features: ['WiFi', 'Bluetooth', 'USB-C', 'Premium'],
    netPrice: 8129.27,
    grossPrice: 9999,
    vatRate: 23,
    currency: 'PLN',
    isAvailable: true,
    isLimited: false,
    stock: null,
    minCartQty: 1,
    maxCartQty: 2,
  },
  {
    id: 'p-2',
    name: 'Galaxy S24 Ultra',
    sku: 'SGS24U256',
    description: '',
    manufacturer: 'Samsung',
    category: 'Telefony',
    features: ['WiFi', 'Bluetooth', 'USB-C', 'Wodoodporny'],
    netPrice: 5121.14,
    grossPrice: 6299,
    vatRate: 23,
    currency: 'PLN',
    isAvailable: true,
    isLimited: true,
    stock: 45,
    minCartQty: 1,
    maxCartQty: 3,
  },
  {
    id: 'p-3',
    name: 'Sony WH-1000XM5',
    sku: 'SNWH1000XM5',
    description: 'Słuchawki z ANC',
    manufacturer: 'Sony',
    category: 'RTV',
    features: ['Bluetooth', 'Bezprzewodowy'],
    netPrice: 1299.19,
    grossPrice: 1599,
    vatRate: 23,
    currency: 'PLN',
    isAvailable: true,
    isLimited: false,
    stock: null,
    minCartQty: 1,
    maxCartQty: 5,
  },
  {
    id: 'p-4',
    name: 'Bosch Serie 6 WAU28P40',
    sku: 'BSWAU28P40',
    description: 'Pralka ładowana od frontu',
    manufacturer: 'Bosch',
    category: 'AGD',
    features: ['Ekologiczny'],
    netPrice: 2674.8,
    grossPrice: 3299,
    vatRate: 23,
    currency: 'PLN',
    isAvailable: false,
    isLimited: true,
    stock: 0,
    minCartQty: 1,
    maxCartQty: 1,
  },
  {
    id: 'p-5',
    name: 'Xiaomi Smart Band 8',
    sku: 'XMSB8BLK',
    description: '',
    manufacturer: 'Xiaomi',
    category: 'Akcesoria',
    features: ['Bluetooth', 'Wodoodporny'],
    netPrice: 145.53,
    grossPrice: 179,
    vatRate: 23,
    currency: 'PLN',
    isAvailable: true,
    isLimited: false,
    stock: null,
    minCartQty: 1,
    maxCartQty: 10,
  },
]
